language: php

php:
  - 7.0
  - 7.1

env:
  - MONGO_VERSION=stable

before_script:
  - yes '' | pecl -q install -f mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - php vendor/bin/phpunit -c travis.phpunit.xml
  - php vendor/bin/phpmd src xml build/config/phpmd.xml --reportfile build/logs/pmd.xml
  - php vendor/bin/phpcs --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=build/config/phpcs.xml -v ./src/ ./tests/

after_script:
  - php vendor/bin/coveralls
